manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: infused-kim
      url-base: https://github.com/infused-kim

    - name: petejohanson
      url-base: https://github.com/petejohanson

    - name: urob
      url-base: https://github.com/urob

    - name: Haha1609
      url-base: https://github.com/Haha1609

  projects:
    - name: zmk-ps2-trackpoint
      remote: Haha1609
      revision: pr-testing/mouse_ps2_module_base
      import: app/west.yml

    # Module for PS/2 mouse & TP driver
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: infused-kim
      revision: main

  self:
    path: config
